### ISSUE TITLE
Allow keyboard inputs to be configured

### ISSUE THREAD

**Issue by zenorocha** [koenkivits/nesnes#2]
Hey @koenkivits,

First of all, congratulations on this amazing project.

I was wondering if you could expose a method to change the keyboard inputs.

I'm trying to get nesnes to work with the Gamepad API :)

**Comment by koenkivits** [comment]
Hi @zenorocha,

This has actually been on my wish list for a while now, but unfortunately I don't have lot of time to work on this project. However, right now you _can_ access the controllers of a NesNes instance, but it isn't documented yet.

Anyhow, here's how you can currently access the controllers for a NesNes instance:
`nesnes.input.controllers.controller0` (for player 1)
`nesnes.input.controllers.controller1` (for player 2)
(where `nesnes` is an instance of NesNes)

By default this gives you a `StandardController` instance, which has 2 methods:
- `press(button)` to press a button
- `depress(button)` to depress a button

Both methods accept a string ('a', 'b', 'start', 'select', 'left', 'right', 'up', or 'down') as their only argument.

Does this help you? If so, maybe I can clean the text up and add it to the documentation for now.
