### ISSUE TITLE
Increase Size?

### ISSUE THREAD

**Issue by Wazk** [koenkivits/nesnes#8]
is there a way to increase the size of the canvas?

**Comment by koenkivits** [comment]
Sorry I haven't replied before, but you set the canvas dimensions using CSS. :)

**Comment by sapbotgit** [comment]
just for Wazk (maybe late)
Instead of making
`<canvas width="800" height="600"></canvas>`
Do:
`<canvas width="256" height="240" style="width: 800;height: 600;"></canvas>`
